version: '3.8'

services:
  caddy:
    image: caddy:2
    restart: unless-stopped

  db:
    image: mysql:8
    restart: unless-stopped
    env_file: ./server/src/config/.env
    command: --secure-file-priv=NULL
    volumes:
      - ./db_data:/var/lib/mysql

  client:
    build: ./client

  server:
    build: ./server
    depends_on:
      - db
