version: '3.8'

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - client-static-files:/client-static-files

  db:
    image: mysql:8
    restart: always
    env_file: ./server/src/config/.env
    command: --secure-file-priv=NULL
    volumes:
      - ./db_data:/var/lib/mysql

  client:
    build: ./client
    volumes:
      - client-static-files:/app/dist

  server:
    build: ./server
    depends_on:
      - db

volumes:
  client-static-files:
